export type subject =
   "registration"
   | "login"
   | "update_profile"
   | "change_password"
   | "update_note"
   | "reset_password"
   | "image_name"
   | "change_email"
   | "update_task_status"
   | "add_task"
   | "update_plan"